---
title: "A Guide to Crawl-ing with R"
subtitle: "a book based on the 'learning to crawl' workshop(s)"
author: "Josh M. London and Devin S. Johnson"
date: "`r Sys.Date()`"
site: "bookdown::bookdown_site"
description: "This book provides mathematical and statistical background related to the modeling of animal movement from satellite telemetry data as well as pragmatic approaches and examples for implementing analysis with the R package, crawl."
url: "https://jmlondon.github.io/crawl-workshop/"
github-repo: "jmlondon/crawl-workshop"
output:
  bookdown::gitbook:
    lib_dir: assets
    split_by: rmd
    config:
      toc:
        collapse: none
---

## About the Authors {-}

Drs. Josh M. London and Devin S. Johnson are researchers at the NOAA Alaska Fisheries
Science Center's Marine Mammal Laboratory in Seattle, Washington. Dr. London has over
10 years of experience programming and deploying satellite tags on phocid seals. 
He has also developed various workflows for the management of telemetry data in R. 
Dr. Johnson is a leading biometrician with expertise in the analysis of animal
movement. Dr. Johnson is the lead author and developer of the R package `crawl`.

## Preface {-}

This book is being developed simultaneously with a 3-day workshop on the use of the
`crawl` package for analysis of animal movment in R. Significant components of this
book, example code, and content will change. Please use code and examples with
caution and contact the authors before relying on advice, code, or examples for
real-world analysis. Identification of errors is encouraged and folks should open
an [issue via the GitHub repository](https://github.com/jmlondon/crawl-workshop/issues).
We will also accept pull requests for any bug fixes or enhancements.

A significant portion of this book is devoted to the support of the R package
`crawl`. The package is available on [CRAN](https://cran.r-project.org/package=crawl) as well as [GitHub](https://github.com/NMML/crawl).

If you are using `crawl` as part of a publication, please refer to the output from
`citation('crawl')` for an appropriate citation. One should also consider referencing
the original _Ecology_ paper from 2008.

> Johnson, D. S., London, J. M., Lea, M.-A. and Durban, J. W. (2008), 
> CONTINUOUS-TIME CORRELATED RANDOM WALK MODEL FOR ANIMAL TELEMETRY DATA. 
> Ecology, 89: 1208–1215. doi:10.1890/07-1032.1

##### Disclaimer {-}

<sub>This book is a scientific product and is not official communication of the Alaska Fisheries Science Center, the National Oceanic and Atmospheric Administration, or the United States Department of Commerce. All AFSC Marine Mammal Laboratory (AFSC-MML) GitHub project code is provided on an ‘as is’ basis and the user assumes responsibility for its use. AFSC-MML has relinquished control of the information and no longer has responsibility to protect the integrity, confidentiality, or availability of the information. Any claims against the Department of Commerce or Department of Commerce bureaus stemming from the use of this GitHub project will be governed by all applicable Federal law. Any reference to specific commercial products, processes, or services by service mark, trademark, manufacturer, or otherwise, does not constitute or imply their endorsement, recommendation or favoring by the Department of Commerce. The Department of Commerce seal and logo, or the seal and logo of a DOC bureau, shall not be used in any manner to imply endorsement of any commercial product or activity by DOC or the United States Government.</sub>
